### ISSUE TITLE
Interested to join AsiaTik

### ISSUE THREAD

**Issue by AmrDeveloper** [Asiatik/Join_Asiatik#17]
I am interested to join Asiatik community 😎

**Comment by tstreamDOTh** [comment]
Hi @AmrDeveloper. Have sent the invite. 🚀

**Comment by AmrDeveloper** [comment]
done , thanks bro 😄

**Comment by midopooler** [comment]
Hi @tstreamDOTh , Can I get the invite as well? The link is not working currently
